# Generated by Django 2.0.5 on 2018-05-26 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pgcomments', '0002_create_function'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('comments', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pgcomments.Thread')),
            ],
        ),
    ]
