# Generated by Django 2.0.5 on 2018-05-26 14:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
            ],
        ),
    ]
